name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Databricks CLI (official)
      uses: databricks/setup-cli@main

    - name: Configure Databricks Auth
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "DATABRICKS_HOST: $DATABRICKS_HOST"
        echo "DATABRICKS_TOKEN: set"

    - name: Verify connection
      run: databricks workspace list

    - name: Deploy to Azure Databricks
      run: |
        databricks workspace import-dir . \
        /Workspace/Users/sachin.kumar@snp.com/GitDeploy \
        --overwrite
