name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Databricks CLI (official)
      uses: databricks/setup-cli@main

    - name: Authenticate to Azure Databricks
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "Authenticated with host: $DATABRICKS_HOST"

    - name: Deploy repo to Azure Databricks Workspace
      run: |
        databricks workspace import-dir . \
        /Workspace/Users/sachin.kumar@snp.com/GitDeploy \
        --overwrite
